# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'loginpage.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_LoginPage(object):
    def setupUi(self, LoginPage):
        LoginPage.setObjectName("LoginPage")
        LoginPage.resize(600, 400)
        LoginPage.setMinimumSize(QtCore.QSize(600, 400))
        self.tabWidget = QtWidgets.QTabWidget(LoginPage)
        self.tabWidget.setGeometry(QtCore.QRect(0, 0, 600, 400))
        self.tabWidget.setMinimumSize(QtCore.QSize(600, 400))
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.Login = QtWidgets.QPushButton(self.tab)
        self.Login.setGeometry(QtCore.QRect(240, 280, 121, 41))
        self.Login.setObjectName("Login")
        self.formLayoutWidget = QtWidgets.QWidget(self.tab)
        self.formLayoutWidget.setGeometry(QtCore.QRect(90, 60, 411, 171))
        self.formLayoutWidget.setObjectName("formLayoutWidget")
        self.formLayout = QtWidgets.QFormLayout(self.formLayoutWidget)
        self.formLayout.setContentsMargins(0, 0, 0, 0)
        self.formLayout.setObjectName("formLayout")
        self.label_ID = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_ID.setObjectName("label_ID")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_ID)
        self.lineEdit_ID = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.lineEdit_ID.setObjectName("lineEdit_ID")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.lineEdit_ID)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.formLayout.setItem(1, QtWidgets.QFormLayout.FieldRole, spacerItem)
        self.label_passwd = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_passwd.setObjectName("label_passwd")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_passwd)
        self.lineEdit_passwd = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.lineEdit_passwd.setObjectName("lineEdit_passwd")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.lineEdit_passwd)
        self.label_type = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_type.setObjectName("label_type")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.label_type)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.radioButton_user = QtWidgets.QRadioButton(self.formLayoutWidget)
        self.radioButton_user.setObjectName("radioButton_user")
        self.horizontalLayout.addWidget(self.radioButton_user)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.radioButton_rest = QtWidgets.QRadioButton(self.formLayoutWidget)
        self.radioButton_rest.setObjectName("radioButton_rest")
        self.horizontalLayout.addWidget(self.radioButton_rest)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem2)
        self.radioButton_rider = QtWidgets.QRadioButton(self.formLayoutWidget)
        self.radioButton_rider.setObjectName("radioButton_rider")
        self.horizontalLayout.addWidget(self.radioButton_rider)
        self.formLayout.setLayout(4, QtWidgets.QFormLayout.FieldRole, self.horizontalLayout)
        spacerItem3 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.formLayout.setItem(3, QtWidgets.QFormLayout.FieldRole, spacerItem3)
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.formLayoutWidget_2 = QtWidgets.QWidget(self.tab_2)
        self.formLayoutWidget_2.setGeometry(QtCore.QRect(90, 60, 411, 171))
        self.formLayoutWidget_2.setObjectName("formLayoutWidget_2")
        self.formLayout_2 = QtWidgets.QFormLayout(self.formLayoutWidget_2)
        self.formLayout_2.setContentsMargins(0, 0, 0, 0)
        self.formLayout_2.setObjectName("formLayout_2")
        self.label_ID_ = QtWidgets.QLabel(self.formLayoutWidget_2)
        self.label_ID_.setObjectName("label_ID_")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_ID_)
        self.lineEdit_ID_ = QtWidgets.QLineEdit(self.formLayoutWidget_2)
        self.lineEdit_ID_.setObjectName("lineEdit_ID_")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.lineEdit_ID_)
        spacerItem4 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.formLayout_2.setItem(1, QtWidgets.QFormLayout.FieldRole, spacerItem4)
        self.label_passwd_ = QtWidgets.QLabel(self.formLayoutWidget_2)
        self.label_passwd_.setObjectName("label_passwd_")
        self.formLayout_2.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_passwd_)
        self.lineEdit_passwd_ = QtWidgets.QLineEdit(self.formLayoutWidget_2)
        self.lineEdit_passwd_.setObjectName("lineEdit_passwd_")
        self.formLayout_2.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.lineEdit_passwd_)
        spacerItem5 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.formLayout_2.setItem(3, QtWidgets.QFormLayout.FieldRole, spacerItem5)
        self.label_type_ = QtWidgets.QLabel(self.formLayoutWidget_2)
        self.label_type_.setObjectName("label_type_")
        self.formLayout_2.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.label_type_)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.radioButton_user_ = QtWidgets.QRadioButton(self.formLayoutWidget_2)
        self.radioButton_user_.setObjectName("radioButton_user_")
        self.horizontalLayout_2.addWidget(self.radioButton_user_)
        spacerItem6 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem6)
        self.radioButton_rest_ = QtWidgets.QRadioButton(self.formLayoutWidget_2)
        self.radioButton_rest_.setObjectName("radioButton_rest_")
        self.horizontalLayout_2.addWidget(self.radioButton_rest_)
        spacerItem7 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem7)
        self.radioButton_rider_ = QtWidgets.QRadioButton(self.formLayoutWidget_2)
        self.radioButton_rider_.setObjectName("radioButton_rider_")
        self.horizontalLayout_2.addWidget(self.radioButton_rider_)
        self.formLayout_2.setLayout(4, QtWidgets.QFormLayout.FieldRole, self.horizontalLayout_2)
        self.Register = QtWidgets.QPushButton(self.tab_2)
        self.Register.setGeometry(QtCore.QRect(240, 280, 121, 41))
        self.Register.setObjectName("Register")
        self.tabWidget.addTab(self.tab_2, "")

        self.retranslateUi(LoginPage)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(LoginPage)

    def retranslateUi(self, LoginPage):
        _translate = QtCore.QCoreApplication.translate
        LoginPage.setWindowTitle(_translate("LoginPage", "Dialog"))
        self.Login.setText(_translate("LoginPage", "Login"))
        self.label_ID.setText(_translate("LoginPage", "user ID:     "))
        self.label_passwd.setText(_translate("LoginPage", "password:    "))
        self.label_type.setText(_translate("LoginPage", "type:    "))
        self.radioButton_user.setText(_translate("LoginPage", "User"))
        self.radioButton_rest.setText(_translate("LoginPage", "Rest"))
        self.radioButton_rider.setText(_translate("LoginPage", "Rider"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("LoginPage", "Login"))
        self.label_ID_.setText(_translate("LoginPage", "user ID:     "))
        self.label_passwd_.setText(_translate("LoginPage", "password:   "))
        self.label_type_.setText(_translate("LoginPage", "type:  "))
        self.radioButton_user_.setText(_translate("LoginPage", "User"))
        self.radioButton_rest_.setText(_translate("LoginPage", "Rest"))
        self.radioButton_rider_.setText(_translate("LoginPage", "Rider"))
        self.Register.setText(_translate("LoginPage", "Register"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("LoginPage", "Register"))

