# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'restpage.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_RestPage(object):
    def setupUi(self, RestPage):
        RestPage.setObjectName("RestPage")
        RestPage.resize(800, 600)
        RestPage.setMinimumSize(QtCore.QSize(800, 600))
        RestPage.setMaximumSize(QtCore.QSize(800, 600))
        self.tabWidget = QtWidgets.QTabWidget(RestPage)
        self.tabWidget.setGeometry(QtCore.QRect(0, 0, 800, 600))
        self.tabWidget.setMinimumSize(QtCore.QSize(800, 600))
        self.tabWidget.setMaximumSize(QtCore.QSize(800, 600))
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.tableWidget_course = QtWidgets.QTableWidget(self.tab)
        self.tableWidget_course.setGeometry(QtCore.QRect(30, 20, 351, 451))
        self.tableWidget_course.setObjectName("tableWidget_course")
        self.tableWidget_course.setColumnCount(2)
        self.tableWidget_course.setRowCount(2)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_course.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_course.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_course.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_course.setHorizontalHeaderItem(1, item)
        self.horizontalLayoutWidget = QtWidgets.QWidget(self.tab)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(29, 489, 731, 51))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.addCourse = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.addCourse.setObjectName("addCourse")
        self.horizontalLayout.addWidget(self.addCourse)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.editCourse = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.editCourse.setObjectName("editCourse")
        self.horizontalLayout.addWidget(self.editCourse)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem2)
        self.uploadPicture = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.uploadPicture.setObjectName("uploadPicture")
        self.horizontalLayout.addWidget(self.uploadPicture)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem3)
        self.deleteCourse = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.deleteCourse.setObjectName("deleteCourse")
        self.horizontalLayout.addWidget(self.deleteCourse)
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem4)
        self.graphicsView = QtWidgets.QGraphicsView(self.tab)
        self.graphicsView.setGeometry(QtCore.QRect(410, 40, 361, 431))
        self.graphicsView.setObjectName("graphicsView")
        self.label_12 = QtWidgets.QLabel(self.tab)
        self.label_12.setGeometry(QtCore.QRect(410, 20, 121, 16))
        self.label_12.setObjectName("label_12")
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.tableWidget_order = QtWidgets.QTableWidget(self.tab_2)
        self.tableWidget_order.setGeometry(QtCore.QRect(30, 40, 401, 441))
        self.tableWidget_order.setObjectName("tableWidget_order")
        self.tableWidget_order.setColumnCount(5)
        self.tableWidget_order.setRowCount(2)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_order.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_order.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_order.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_order.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_order.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_order.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_order.setHorizontalHeaderItem(4, item)
        self.horizontalLayoutWidget_2 = QtWidgets.QWidget(self.tab_2)
        self.horizontalLayoutWidget_2.setGeometry(QtCore.QRect(30, 500, 731, 41))
        self.horizontalLayoutWidget_2.setObjectName("horizontalLayoutWidget_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_2)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem5)
        self.acceptOrder = QtWidgets.QPushButton(self.horizontalLayoutWidget_2)
        self.acceptOrder.setObjectName("acceptOrder")
        self.horizontalLayout_2.addWidget(self.acceptOrder)
        spacerItem6 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem6)
        self.rejectOrder = QtWidgets.QPushButton(self.horizontalLayoutWidget_2)
        self.rejectOrder.setObjectName("rejectOrder")
        self.horizontalLayout_2.addWidget(self.rejectOrder)
        spacerItem7 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem7)
        self.label_13 = QtWidgets.QLabel(self.tab_2)
        self.label_13.setGeometry(QtCore.QRect(30, 20, 141, 16))
        self.label_13.setObjectName("label_13")
        self.tableWidget_rider = QtWidgets.QTableWidget(self.tab_2)
        self.tableWidget_rider.setGeometry(QtCore.QRect(460, 40, 301, 401))
        self.tableWidget_rider.setObjectName("tableWidget_rider")
        self.tableWidget_rider.setColumnCount(3)
        self.tableWidget_rider.setRowCount(2)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_rider.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_rider.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_rider.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_rider.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_rider.setHorizontalHeaderItem(2, item)
        self.sortRiderByDistance = QtWidgets.QPushButton(self.tab_2)
        self.sortRiderByDistance.setGeometry(QtCore.QRect(460, 450, 301, 28))
        self.sortRiderByDistance.setObjectName("sortRiderByDistance")
        self.tabWidget.addTab(self.tab_2, "")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.tableWidget_history = QtWidgets.QTableWidget(self.tab_3)
        self.tableWidget_history.setGeometry(QtCore.QRect(30, 90, 731, 291))
        self.tableWidget_history.setObjectName("tableWidget_history")
        self.tableWidget_history.setColumnCount(5)
        self.tableWidget_history.setRowCount(2)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_history.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_history.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_history.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_history.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_history.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_history.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_history.setHorizontalHeaderItem(4, item)
        self.comment = QtWidgets.QTextBrowser(self.tab_3)
        self.comment.setGeometry(QtCore.QRect(30, 420, 731, 121))
        self.comment.setObjectName("comment")
        self.label = QtWidgets.QLabel(self.tab_3)
        self.label.setGeometry(QtCore.QRect(30, 390, 71, 21))
        self.label.setObjectName("label")
        self.horizontalLayoutWidget_3 = QtWidgets.QWidget(self.tab_3)
        self.horizontalLayoutWidget_3.setGeometry(QtCore.QRect(30, 20, 641, 31))
        self.horizontalLayoutWidget_3.setObjectName("horizontalLayoutWidget_3")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_3)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_2 = QtWidgets.QLabel(self.horizontalLayoutWidget_3)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_3.addWidget(self.label_2)
        spacerItem8 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem8)
        self.comboBox_time = QtWidgets.QComboBox(self.horizontalLayoutWidget_3)
        self.comboBox_time.setObjectName("comboBox_time")
        self.comboBox_time.addItem("")
        self.comboBox_time.addItem("")
        self.comboBox_time.addItem("")
        self.comboBox_time.addItem("")
        self.horizontalLayout_3.addWidget(self.comboBox_time)
        spacerItem9 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem9)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.lineEdit_timeStart = QtWidgets.QLineEdit(self.horizontalLayoutWidget_3)
        self.lineEdit_timeStart.setObjectName("lineEdit_timeStart")
        self.horizontalLayout_4.addWidget(self.lineEdit_timeStart)
        self.label_3 = QtWidgets.QLabel(self.horizontalLayoutWidget_3)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_4.addWidget(self.label_3)
        self.lineEdit_timeEnd = QtWidgets.QLineEdit(self.horizontalLayoutWidget_3)
        self.lineEdit_timeEnd.setObjectName("lineEdit_timeEnd")
        self.horizontalLayout_4.addWidget(self.lineEdit_timeEnd)
        self.horizontalLayout_3.addLayout(self.horizontalLayout_4)
        self.horizontalLayoutWidget_6 = QtWidgets.QWidget(self.tab_3)
        self.horizontalLayoutWidget_6.setGeometry(QtCore.QRect(30, 50, 641, 31))
        self.horizontalLayoutWidget_6.setObjectName("horizontalLayoutWidget_6")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_6)
        self.horizontalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.label_10 = QtWidgets.QLabel(self.horizontalLayoutWidget_6)
        self.label_10.setObjectName("label_10")
        self.horizontalLayout_6.addWidget(self.label_10)
        spacerItem10 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem10)
        self.comboBox_score = QtWidgets.QComboBox(self.horizontalLayoutWidget_6)
        self.comboBox_score.setObjectName("comboBox_score")
        self.comboBox_score.addItem("")
        self.comboBox_score.addItem("")
        self.comboBox_score.addItem("")
        self.comboBox_score.addItem("")
        self.horizontalLayout_6.addWidget(self.comboBox_score)
        spacerItem11 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem11)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.lineEdit_scoreStart = QtWidgets.QLineEdit(self.horizontalLayoutWidget_6)
        self.lineEdit_scoreStart.setObjectName("lineEdit_scoreStart")
        self.horizontalLayout_7.addWidget(self.lineEdit_scoreStart)
        self.label_11 = QtWidgets.QLabel(self.horizontalLayoutWidget_6)
        self.label_11.setObjectName("label_11")
        self.horizontalLayout_7.addWidget(self.label_11)
        self.lineEdit_scoreEnd = QtWidgets.QLineEdit(self.horizontalLayoutWidget_6)
        self.lineEdit_scoreEnd.setObjectName("lineEdit_scoreEnd")
        self.horizontalLayout_7.addWidget(self.lineEdit_scoreEnd)
        self.horizontalLayout_6.addLayout(self.horizontalLayout_7)
        self.filter = QtWidgets.QPushButton(self.tab_3)
        self.filter.setGeometry(QtCore.QRect(680, 20, 81, 61))
        self.filter.setObjectName("filter")
        self.score = QtWidgets.QLabel(self.tab_3)
        self.score.setGeometry(QtCore.QRect(110, 390, 72, 21))
        self.score.setObjectName("score")
        self.tabWidget.addTab(self.tab_3, "")
        self.tab_4 = QtWidgets.QWidget()
        self.tab_4.setObjectName("tab_4")
        self.formLayoutWidget = QtWidgets.QWidget(self.tab_4)
        self.formLayoutWidget.setGeometry(QtCore.QRect(80, 30, 631, 441))
        self.formLayoutWidget.setObjectName("formLayoutWidget")
        self.formLayout = QtWidgets.QFormLayout(self.formLayoutWidget)
        self.formLayout.setContentsMargins(0, 0, 0, 0)
        self.formLayout.setObjectName("formLayout")
        self.label_4 = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_4.setObjectName("label_4")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_4)
        self.restID = QtWidgets.QLabel(self.formLayoutWidget)
        self.restID.setText("")
        self.restID.setObjectName("restID")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.restID)
        spacerItem12 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.formLayout.setItem(1, QtWidgets.QFormLayout.LabelRole, spacerItem12)
        self.label_8 = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_8.setObjectName("label_8")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_8)
        self.lineEdit_restName = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.lineEdit_restName.setObjectName("lineEdit_restName")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.lineEdit_restName)
        spacerItem13 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.formLayout.setItem(3, QtWidgets.QFormLayout.LabelRole, spacerItem13)
        self.label_7 = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_7.setObjectName("label_7")
        self.formLayout.setWidget(6, QtWidgets.QFormLayout.LabelRole, self.label_7)
        self.Address = QtWidgets.QTextEdit(self.formLayoutWidget)
        self.Address.setObjectName("Address")
        self.formLayout.setWidget(6, QtWidgets.QFormLayout.FieldRole, self.Address)
        spacerItem14 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.formLayout.setItem(7, QtWidgets.QFormLayout.LabelRole, spacerItem14)
        self.label_5 = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_5.setObjectName("label_5")
        self.formLayout.setWidget(8, QtWidgets.QFormLayout.LabelRole, self.label_5)
        self.lineEdit_restLongitude = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.lineEdit_restLongitude.setObjectName("lineEdit_restLongitude")
        self.formLayout.setWidget(8, QtWidgets.QFormLayout.FieldRole, self.lineEdit_restLongitude)
        spacerItem15 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.formLayout.setItem(9, QtWidgets.QFormLayout.LabelRole, spacerItem15)
        self.label_6 = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_6.setObjectName("label_6")
        self.formLayout.setWidget(10, QtWidgets.QFormLayout.LabelRole, self.label_6)
        self.lineEdit_restLatitude = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.lineEdit_restLatitude.setObjectName("lineEdit_restLatitude")
        self.formLayout.setWidget(10, QtWidgets.QFormLayout.FieldRole, self.lineEdit_restLatitude)
        self.label_14 = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_14.setObjectName("label_14")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.label_14)
        self.lineEdit_restTel = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.lineEdit_restTel.setObjectName("lineEdit_restTel")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.lineEdit_restTel)
        spacerItem16 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.formLayout.setItem(5, QtWidgets.QFormLayout.LabelRole, spacerItem16)
        self.horizontalLayoutWidget_5 = QtWidgets.QWidget(self.tab_4)
        self.horizontalLayoutWidget_5.setGeometry(QtCore.QRect(80, 500, 631, 41))
        self.horizontalLayoutWidget_5.setObjectName("horizontalLayoutWidget_5")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_5)
        self.horizontalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        spacerItem17 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem17)
        self.saveChange = QtWidgets.QPushButton(self.horizontalLayoutWidget_5)
        self.saveChange.setObjectName("saveChange")
        self.horizontalLayout_5.addWidget(self.saveChange)
        spacerItem18 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem18)
        self.abandonChange = QtWidgets.QPushButton(self.horizontalLayoutWidget_5)
        self.abandonChange.setObjectName("abandonChange")
        self.horizontalLayout_5.addWidget(self.abandonChange)
        spacerItem19 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem19)
        self.tabWidget.addTab(self.tab_4, "")

        self.retranslateUi(RestPage)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(RestPage)

    def retranslateUi(self, RestPage):
        _translate = QtCore.QCoreApplication.translate
        RestPage.setWindowTitle(_translate("RestPage", "Dialog"))
        item = self.tableWidget_course.verticalHeaderItem(0)
        item.setText(_translate("RestPage", "course01"))
        item = self.tableWidget_course.verticalHeaderItem(1)
        item.setText(_translate("RestPage", "course02"))
        item = self.tableWidget_course.horizontalHeaderItem(0)
        item.setText(_translate("RestPage", "name"))
        item = self.tableWidget_course.horizontalHeaderItem(1)
        item.setText(_translate("RestPage", "price"))
        self.addCourse.setText(_translate("RestPage", "add"))
        self.editCourse.setText(_translate("RestPage", "edit"))
        self.uploadPicture.setText(_translate("RestPage", "upload picture"))
        self.deleteCourse.setText(_translate("RestPage", "delete"))
        self.label_12.setText(_translate("RestPage", "course picture"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("RestPage", "course_manage"))
        item = self.tableWidget_order.verticalHeaderItem(0)
        item.setText(_translate("RestPage", "order01"))
        item = self.tableWidget_order.verticalHeaderItem(1)
        item.setText(_translate("RestPage", "order02"))
        item = self.tableWidget_order.horizontalHeaderItem(0)
        item.setText(_translate("RestPage", "user"))
        item = self.tableWidget_order.horizontalHeaderItem(1)
        item.setText(_translate("RestPage", "LocX"))
        item = self.tableWidget_order.horizontalHeaderItem(2)
        item.setText(_translate("RestPage", "LocY"))
        item = self.tableWidget_order.horizontalHeaderItem(3)
        item.setText(_translate("RestPage", "price"))
        item = self.tableWidget_order.horizontalHeaderItem(4)
        item.setText(_translate("RestPage", "time"))
        self.acceptOrder.setText(_translate("RestPage", "accept"))
        self.rejectOrder.setText(_translate("RestPage", "reject"))
        self.label_13.setText(_translate("RestPage", "waiting orders:"))
        item = self.tableWidget_rider.verticalHeaderItem(0)
        item.setText(_translate("RestPage", "rider01"))
        item = self.tableWidget_rider.verticalHeaderItem(1)
        item.setText(_translate("RestPage", "rider02"))
        item = self.tableWidget_rider.horizontalHeaderItem(0)
        item.setText(_translate("RestPage", "longitude"))
        item = self.tableWidget_rider.horizontalHeaderItem(1)
        item.setText(_translate("RestPage", "latitude"))
        item = self.tableWidget_rider.horizontalHeaderItem(2)
        item.setText(_translate("RestPage", "distance"))
        self.sortRiderByDistance.setText(_translate("RestPage", "sort by distance"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("RestPage", "take order"))
        item = self.tableWidget_history.verticalHeaderItem(0)
        item.setText(_translate("RestPage", "history_order01"))
        item = self.tableWidget_history.verticalHeaderItem(1)
        item.setText(_translate("RestPage", "history_order02"))
        item = self.tableWidget_history.horizontalHeaderItem(0)
        item.setText(_translate("RestPage", "price"))
        item = self.tableWidget_history.horizontalHeaderItem(1)
        item.setText(_translate("RestPage", "user"))
        item = self.tableWidget_history.horizontalHeaderItem(2)
        item.setText(_translate("RestPage", "rider"))
        item = self.tableWidget_history.horizontalHeaderItem(3)
        item.setText(_translate("RestPage", "time"))
        item = self.tableWidget_history.horizontalHeaderItem(4)
        item.setText(_translate("RestPage", "score"))
        self.label.setText(_translate("RestPage", "comment:"))
        self.label_2.setText(_translate("RestPage", "filter by time"))
        self.comboBox_time.setItemText(0, _translate("RestPage", "all orders"))
        self.comboBox_time.setItemText(1, _translate("RestPage", "orders in this year"))
        self.comboBox_time.setItemText(2, _translate("RestPage", "orders in this month"))
        self.comboBox_time.setItemText(3, _translate("RestPage", "orders in this week"))
        self.label_3.setText(_translate("RestPage", "to"))
        self.label_10.setText(_translate("RestPage", "filter by score"))
        self.comboBox_score.setItemText(0, _translate("RestPage", "all orders"))
        self.comboBox_score.setItemText(1, _translate("RestPage", "orders in this year"))
        self.comboBox_score.setItemText(2, _translate("RestPage", "orders in this month"))
        self.comboBox_score.setItemText(3, _translate("RestPage", "orders in this week"))
        self.label_11.setText(_translate("RestPage", "to"))
        self.filter.setText(_translate("RestPage", "filter"))
        self.score.setText(_translate("RestPage", "/5"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("RestPage", "history_order_browse"))
        self.label_4.setText(_translate("RestPage", "restaurant ID:     "))
        self.label_8.setText(_translate("RestPage", "restaurant name:   "))
        self.label_7.setText(_translate("RestPage", "restaurant address:"))
        self.label_5.setText(_translate("RestPage", "restaurant longitude:   "))
        self.label_6.setText(_translate("RestPage", "restaurant latitude"))
        self.label_14.setText(_translate("RestPage", "restauranat Tel:"))
        self.saveChange.setText(_translate("RestPage", "save change"))
        self.abandonChange.setText(_translate("RestPage", "abandon change"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_4), _translate("RestPage", "restaurant information edit"))

