# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\restpage.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_RestPage(object):
    def setupUi(self, RestPage):
        RestPage.setObjectName("RestPage")
        RestPage.resize(800, 600)
        RestPage.setMinimumSize(QtCore.QSize(800, 600))
        RestPage.setMaximumSize(QtCore.QSize(800, 600))
        self.tabWidget = QtWidgets.QTabWidget(RestPage)
        self.tabWidget.setGeometry(QtCore.QRect(0, 0, 800, 600))
        self.tabWidget.setMinimumSize(QtCore.QSize(800, 600))
        self.tabWidget.setMaximumSize(QtCore.QSize(800, 600))
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.tableWidget_course = QtWidgets.QTableWidget(self.tab)
        self.tableWidget_course.setGeometry(QtCore.QRect(30, 20, 341, 391))
        self.tableWidget_course.setObjectName("tableWidget_course")
        self.tableWidget_course.setColumnCount(2)
        self.tableWidget_course.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_course.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_course.setHorizontalHeaderItem(1, item)
        self.tableWidget_course.horizontalHeader().setDefaultSectionSize(110)
        self.tableWidget_course.horizontalHeader().setStretchLastSection(True)
        self.horizontalLayoutWidget = QtWidgets.QWidget(self.tab)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(30, 490, 731, 51))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.addCourse = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.addCourse.setObjectName("addCourse")
        self.horizontalLayout.addWidget(self.addCourse)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.saveCourse = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.saveCourse.setObjectName("saveCourse")
        self.horizontalLayout.addWidget(self.saveCourse)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem2)
        self.deleteCourse = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.deleteCourse.setObjectName("deleteCourse")
        self.horizontalLayout.addWidget(self.deleteCourse)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem3)
        self.graphicsView = QtWidgets.QGraphicsView(self.tab)
        self.graphicsView.setGeometry(QtCore.QRect(410, 40, 361, 371))
        self.graphicsView.setObjectName("graphicsView")
        self.label_12 = QtWidgets.QLabel(self.tab)
        self.label_12.setGeometry(QtCore.QRect(410, 20, 121, 16))
        self.label_12.setObjectName("label_12")
        self.horizontalLayoutWidget_3 = QtWidgets.QWidget(self.tab)
        self.horizontalLayoutWidget_3.setGeometry(QtCore.QRect(30, 420, 731, 61))
        self.horizontalLayoutWidget_3.setObjectName("horizontalLayoutWidget_3")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_3)
        self.horizontalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem4)
        self.courseName = QtWidgets.QLabel(self.horizontalLayoutWidget_3)
        self.courseName.setObjectName("courseName")
        self.horizontalLayout_4.addWidget(self.courseName)
        self.courseNameEdit = QtWidgets.QLineEdit(self.horizontalLayoutWidget_3)
        self.courseNameEdit.setObjectName("courseNameEdit")
        self.horizontalLayout_4.addWidget(self.courseNameEdit)
        self.coursePrice = QtWidgets.QLabel(self.horizontalLayoutWidget_3)
        self.coursePrice.setObjectName("coursePrice")
        self.horizontalLayout_4.addWidget(self.coursePrice)
        self.coursePriceEdit = QtWidgets.QLineEdit(self.horizontalLayoutWidget_3)
        self.coursePriceEdit.setObjectName("coursePriceEdit")
        self.horizontalLayout_4.addWidget(self.coursePriceEdit)
        self.coursePhoto = QtWidgets.QLabel(self.horizontalLayoutWidget_3)
        self.coursePhoto.setObjectName("coursePhoto")
        self.horizontalLayout_4.addWidget(self.coursePhoto)
        self.coursePhotoEdit = QtWidgets.QLineEdit(self.horizontalLayoutWidget_3)
        self.coursePhotoEdit.setObjectName("coursePhotoEdit")
        self.horizontalLayout_4.addWidget(self.coursePhotoEdit)
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem5)
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.tableWidget_order = QtWidgets.QTableWidget(self.tab_2)
        self.tableWidget_order.setGeometry(QtCore.QRect(50, 50, 451, 261))
        self.tableWidget_order.setObjectName("tableWidget_order")
        self.tableWidget_order.setColumnCount(4)
        self.tableWidget_order.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_order.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_order.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_order.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_order.setHorizontalHeaderItem(3, item)
        self.tableWidget_order.horizontalHeader().setCascadingSectionResizes(False)
        self.tableWidget_order.horizontalHeader().setDefaultSectionSize(110)
        self.tableWidget_order.horizontalHeader().setStretchLastSection(True)
        self.tableWidget_order.verticalHeader().setStretchLastSection(False)
        self.horizontalLayoutWidget_2 = QtWidgets.QWidget(self.tab_2)
        self.horizontalLayoutWidget_2.setGeometry(QtCore.QRect(30, 380, 731, 41))
        self.horizontalLayoutWidget_2.setObjectName("horizontalLayoutWidget_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_2)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        spacerItem6 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem6)
        self.acceptOrder = QtWidgets.QPushButton(self.horizontalLayoutWidget_2)
        self.acceptOrder.setObjectName("acceptOrder")
        self.horizontalLayout_2.addWidget(self.acceptOrder)
        spacerItem7 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem7)
        self.rejectOrder = QtWidgets.QPushButton(self.horizontalLayoutWidget_2)
        self.rejectOrder.setObjectName("rejectOrder")
        self.horizontalLayout_2.addWidget(self.rejectOrder)
        spacerItem8 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem8)
        self.label_13 = QtWidgets.QLabel(self.tab_2)
        self.label_13.setGeometry(QtCore.QRect(30, 20, 141, 16))
        self.label_13.setObjectName("label_13")
        self.listWidget_orderCourse = QtWidgets.QListWidget(self.tab_2)
        self.listWidget_orderCourse.setGeometry(QtCore.QRect(520, 50, 256, 261))
        self.listWidget_orderCourse.setObjectName("listWidget_orderCourse")
        self.tableWidget_order.raise_()
        self.horizontalLayoutWidget_2.raise_()
        self.label_13.raise_()
        self.listWidget_orderCourse.raise_()
        self.tabWidget.addTab(self.tab_2, "")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.tableWidget_history = QtWidgets.QTableWidget(self.tab_3)
        self.tableWidget_history.setGeometry(QtCore.QRect(30, 90, 731, 281))
        self.tableWidget_history.setObjectName("tableWidget_history")
        self.tableWidget_history.setColumnCount(4)
        self.tableWidget_history.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_history.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_history.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_history.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_history.setHorizontalHeaderItem(3, item)
        self.tableWidget_history.horizontalHeader().setDefaultSectionSize(100)
        self.comment = QtWidgets.QTextBrowser(self.tab_3)
        self.comment.setGeometry(QtCore.QRect(30, 420, 731, 121))
        self.comment.setObjectName("comment")
        self.label = QtWidgets.QLabel(self.tab_3)
        self.label.setGeometry(QtCore.QRect(30, 390, 71, 21))
        self.label.setObjectName("label")
        self.score = QtWidgets.QLabel(self.tab_3)
        self.score.setGeometry(QtCore.QRect(110, 390, 72, 21))
        self.score.setObjectName("score")
        self.tabWidget.addTab(self.tab_3, "")
        self.tab_4 = QtWidgets.QWidget()
        self.tab_4.setObjectName("tab_4")
        self.formLayoutWidget = QtWidgets.QWidget(self.tab_4)
        self.formLayoutWidget.setGeometry(QtCore.QRect(80, 30, 631, 441))
        self.formLayoutWidget.setObjectName("formLayoutWidget")
        self.formLayout = QtWidgets.QFormLayout(self.formLayoutWidget)
        self.formLayout.setContentsMargins(0, 0, 0, 0)
        self.formLayout.setObjectName("formLayout")
        self.label_4 = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_4.setObjectName("label_4")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_4)
        self.label_restID = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_restID.setText("")
        self.label_restID.setObjectName("label_restID")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.label_restID)
        spacerItem9 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.formLayout.setItem(1, QtWidgets.QFormLayout.LabelRole, spacerItem9)
        self.label_8 = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_8.setObjectName("label_8")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_8)
        self.lineEdit_restName = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.lineEdit_restName.setObjectName("lineEdit_restName")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.lineEdit_restName)
        spacerItem10 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.formLayout.setItem(3, QtWidgets.QFormLayout.LabelRole, spacerItem10)
        self.label_7 = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_7.setObjectName("label_7")
        self.formLayout.setWidget(6, QtWidgets.QFormLayout.LabelRole, self.label_7)
        self.Address = QtWidgets.QTextEdit(self.formLayoutWidget)
        self.Address.setObjectName("Address")
        self.formLayout.setWidget(6, QtWidgets.QFormLayout.FieldRole, self.Address)
        spacerItem11 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.formLayout.setItem(7, QtWidgets.QFormLayout.LabelRole, spacerItem11)
        self.label_5 = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_5.setObjectName("label_5")
        self.formLayout.setWidget(8, QtWidgets.QFormLayout.LabelRole, self.label_5)
        self.lineEdit_restLongitude = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.lineEdit_restLongitude.setObjectName("lineEdit_restLongitude")
        self.formLayout.setWidget(8, QtWidgets.QFormLayout.FieldRole, self.lineEdit_restLongitude)
        spacerItem12 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.formLayout.setItem(9, QtWidgets.QFormLayout.LabelRole, spacerItem12)
        self.label_6 = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_6.setObjectName("label_6")
        self.formLayout.setWidget(10, QtWidgets.QFormLayout.LabelRole, self.label_6)
        self.lineEdit_restLatitude = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.lineEdit_restLatitude.setObjectName("lineEdit_restLatitude")
        self.formLayout.setWidget(10, QtWidgets.QFormLayout.FieldRole, self.lineEdit_restLatitude)
        self.label_14 = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_14.setObjectName("label_14")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.label_14)
        self.lineEdit_restTel = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.lineEdit_restTel.setObjectName("lineEdit_restTel")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.lineEdit_restTel)
        spacerItem13 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.formLayout.setItem(5, QtWidgets.QFormLayout.LabelRole, spacerItem13)
        self.horizontalLayoutWidget_5 = QtWidgets.QWidget(self.tab_4)
        self.horizontalLayoutWidget_5.setGeometry(QtCore.QRect(80, 500, 631, 41))
        self.horizontalLayoutWidget_5.setObjectName("horizontalLayoutWidget_5")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_5)
        self.horizontalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        spacerItem14 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem14)
        self.saveChange = QtWidgets.QPushButton(self.horizontalLayoutWidget_5)
        self.saveChange.setObjectName("saveChange")
        self.horizontalLayout_5.addWidget(self.saveChange)
        spacerItem15 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem15)
        self.abandonChange = QtWidgets.QPushButton(self.horizontalLayoutWidget_5)
        self.abandonChange.setObjectName("abandonChange")
        self.horizontalLayout_5.addWidget(self.abandonChange)
        spacerItem16 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem16)
        self.tabWidget.addTab(self.tab_4, "")

        self.retranslateUi(RestPage)
        self.tabWidget.setCurrentIndex(3)
        QtCore.QMetaObject.connectSlotsByName(RestPage)

    def retranslateUi(self, RestPage):
        _translate = QtCore.QCoreApplication.translate
        RestPage.setWindowTitle(_translate("RestPage", "Dialog"))
        item = self.tableWidget_course.horizontalHeaderItem(0)
        item.setText(_translate("RestPage", "name"))
        item = self.tableWidget_course.horizontalHeaderItem(1)
        item.setText(_translate("RestPage", "price"))
        self.addCourse.setText(_translate("RestPage", "add"))
        self.saveCourse.setText(_translate("RestPage", "save"))
        self.deleteCourse.setText(_translate("RestPage", "delete"))
        self.label_12.setText(_translate("RestPage", "course picture"))
        self.courseName.setText(_translate("RestPage", "name"))
        self.coursePrice.setText(_translate("RestPage", "price"))
        self.coursePhoto.setText(_translate("RestPage", "photo"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("RestPage", "course_manage"))
        item = self.tableWidget_order.horizontalHeaderItem(0)
        item.setText(_translate("RestPage", "user"))
        item = self.tableWidget_order.horizontalHeaderItem(1)
        item.setText(_translate("RestPage", "time"))
        item = self.tableWidget_order.horizontalHeaderItem(2)
        item.setText(_translate("RestPage", "status"))
        item = self.tableWidget_order.horizontalHeaderItem(3)
        item.setText(_translate("RestPage", "rider"))
        self.acceptOrder.setText(_translate("RestPage", "accept"))
        self.rejectOrder.setText(_translate("RestPage", "reject"))
        self.label_13.setText(_translate("RestPage", "waiting orders:"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("RestPage", "take order"))
        item = self.tableWidget_history.horizontalHeaderItem(0)
        item.setText(_translate("RestPage", "user"))
        item = self.tableWidget_history.horizontalHeaderItem(1)
        item.setText(_translate("RestPage", "rider"))
        item = self.tableWidget_history.horizontalHeaderItem(2)
        item.setText(_translate("RestPage", "time"))
        item = self.tableWidget_history.horizontalHeaderItem(3)
        item.setText(_translate("RestPage", "score"))
        self.label.setText(_translate("RestPage", "comment:"))
        self.score.setText(_translate("RestPage", "/5"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("RestPage", "history_order_browse"))
        self.label_4.setText(_translate("RestPage", "restaurant ID:     "))
        self.label_8.setText(_translate("RestPage", "restaurant name:   "))
        self.label_7.setText(_translate("RestPage", "restaurant address:"))
        self.label_5.setText(_translate("RestPage", "restaurant longitude:   "))
        self.label_6.setText(_translate("RestPage", "restaurant latitude"))
        self.label_14.setText(_translate("RestPage", "restauranat Tel:"))
        self.saveChange.setText(_translate("RestPage", "save change"))
        self.abandonChange.setText(_translate("RestPage", "abandon change"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_4), _translate("RestPage", "restaurant information edit"))

