# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\riderpage.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_RiderPage(object):
    def setupUi(self, RiderPage):
        RiderPage.setObjectName("RiderPage")
        RiderPage.resize(800, 600)
        RiderPage.setMinimumSize(QtCore.QSize(800, 600))
        RiderPage.setMaximumSize(QtCore.QSize(800, 600))
        self.tabWidget = QtWidgets.QTabWidget(RiderPage)
        self.tabWidget.setGeometry(QtCore.QRect(0, 0, 800, 600))
        self.tabWidget.setMinimumSize(QtCore.QSize(800, 600))
        self.tabWidget.setMaximumSize(QtCore.QSize(800, 600))
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.tableWidget_order = QtWidgets.QTableWidget(self.tab)
        self.tableWidget_order.setGeometry(QtCore.QRect(30, 30, 731, 151))
        self.tableWidget_order.setObjectName("tableWidget_order")
        self.tableWidget_order.setColumnCount(4)
        self.tableWidget_order.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_order.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_order.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_order.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_order.setHorizontalHeaderItem(3, item)
        self.tableWidget_order.horizontalHeader().setDefaultSectionSize(115)
        self.tableWidget_order.horizontalHeader().setStretchLastSection(True)
        self.horizontalLayoutWidget = QtWidgets.QWidget(self.tab)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(30, 470, 731, 51))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.acceptOrder = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.acceptOrder.setObjectName("acceptOrder")
        self.horizontalLayout.addWidget(self.acceptOrder)
        self.rejectOrder = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.rejectOrder.setObjectName("rejectOrder")
        self.horizontalLayout.addWidget(self.rejectOrder)
        self.tableWidget_deliver = QtWidgets.QTableWidget(self.tab)
        self.tableWidget_deliver.setGeometry(QtCore.QRect(30, 210, 731, 231))
        self.tableWidget_deliver.setSelectionMode(QtWidgets.QAbstractItemView.NoSelection)
        self.tableWidget_deliver.setObjectName("tableWidget_deliver")
        self.tableWidget_deliver.setColumnCount(6)
        self.tableWidget_deliver.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_deliver.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_deliver.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_deliver.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_deliver.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_deliver.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_deliver.setHorizontalHeaderItem(5, item)
        self.tableWidget_deliver.horizontalHeader().setDefaultSectionSize(120)
        self.tableWidget_deliver.horizontalHeader().setStretchLastSection(True)
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.graphicsView_map = QtWidgets.QGraphicsView(self.tab_2)
        self.graphicsView_map.setGeometry(QtCore.QRect(80, 40, 611, 411))
        self.graphicsView_map.setObjectName("graphicsView_map")
        self.pushButton_plan = QtWidgets.QPushButton(self.tab_2)
        self.pushButton_plan.setGeometry(QtCore.QRect(200, 490, 93, 28))
        self.pushButton_plan.setObjectName("pushButton_plan")
        self.pushButton_reset = QtWidgets.QPushButton(self.tab_2)
        self.pushButton_reset.setGeometry(QtCore.QRect(410, 490, 93, 28))
        self.pushButton_reset.setObjectName("pushButton_reset")
        self.tabWidget.addTab(self.tab_2, "")
        self.tab_4 = QtWidgets.QWidget()
        self.tab_4.setObjectName("tab_4")
        self.formLayoutWidget = QtWidgets.QWidget(self.tab_4)
        self.formLayoutWidget.setGeometry(QtCore.QRect(80, 120, 631, 161))
        self.formLayoutWidget.setObjectName("formLayoutWidget")
        self.formLayout = QtWidgets.QFormLayout(self.formLayoutWidget)
        self.formLayout.setContentsMargins(0, 0, 0, 0)
        self.formLayout.setObjectName("formLayout")
        self.label_3 = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_3.setObjectName("label_3")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_3)
        self.label_riderID = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_riderID.setText("")
        self.label_riderID.setObjectName("label_riderID")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.label_riderID)
        self.label_5 = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_5.setObjectName("label_5")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_5)
        self.lineEdit_riderName = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.lineEdit_riderName.setObjectName("lineEdit_riderName")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.lineEdit_riderName)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.formLayout.setItem(3, QtWidgets.QFormLayout.FieldRole, spacerItem)
        self.label_6 = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_6.setObjectName("label_6")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.label_6)
        self.lineEdit_riderTel = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.lineEdit_riderTel.setObjectName("lineEdit_riderTel")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.lineEdit_riderTel)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.formLayout.setItem(1, QtWidgets.QFormLayout.FieldRole, spacerItem1)
        self.horizontalLayoutWidget_4 = QtWidgets.QWidget(self.tab_4)
        self.horizontalLayoutWidget_4.setGeometry(QtCore.QRect(80, 380, 631, 71))
        self.horizontalLayoutWidget_4.setObjectName("horizontalLayoutWidget_4")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_4)
        self.horizontalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem2)
        self.saveChange = QtWidgets.QPushButton(self.horizontalLayoutWidget_4)
        self.saveChange.setObjectName("saveChange")
        self.horizontalLayout_4.addWidget(self.saveChange)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem3)
        self.abandonChange = QtWidgets.QPushButton(self.horizontalLayoutWidget_4)
        self.abandonChange.setObjectName("abandonChange")
        self.horizontalLayout_4.addWidget(self.abandonChange)
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem4)
        self.tabWidget.addTab(self.tab_4, "")

        self.retranslateUi(RiderPage)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(RiderPage)

    def retranslateUi(self, RiderPage):
        _translate = QtCore.QCoreApplication.translate
        RiderPage.setWindowTitle(_translate("RiderPage", "Dialog"))
        item = self.tableWidget_order.horizontalHeaderItem(0)
        item.setText(_translate("RiderPage", "user name"))
        item = self.tableWidget_order.horizontalHeaderItem(1)
        item.setText(_translate("RiderPage", "user tel"))
        item = self.tableWidget_order.horizontalHeaderItem(2)
        item.setText(_translate("RiderPage", "restaurant"))
        item = self.tableWidget_order.horizontalHeaderItem(3)
        item.setText(_translate("RiderPage", "order_state"))
        self.acceptOrder.setText(_translate("RiderPage", "accept"))
        self.rejectOrder.setText(_translate("RiderPage", "reject"))
        item = self.tableWidget_deliver.horizontalHeaderItem(0)
        item.setText(_translate("RiderPage", "user name"))
        item = self.tableWidget_deliver.horizontalHeaderItem(1)
        item.setText(_translate("RiderPage", "user tel"))
        item = self.tableWidget_deliver.horizontalHeaderItem(2)
        item.setText(_translate("RiderPage", "address"))
        item = self.tableWidget_deliver.horizontalHeaderItem(3)
        item.setText(_translate("RiderPage", "order time"))
        item = self.tableWidget_deliver.horizontalHeaderItem(4)
        item.setText(_translate("RiderPage", "restaurant"))
        item = self.tableWidget_deliver.horizontalHeaderItem(5)
        item.setText(_translate("RiderPage", "order state"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("RiderPage", "orders waiting"))
        self.pushButton_plan.setText(_translate("RiderPage", "plan"))
        self.pushButton_reset.setText(_translate("RiderPage", "reset"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("RiderPage", "navigation"))
        self.label_3.setText(_translate("RiderPage", "rider ID:      "))
        self.label_5.setText(_translate("RiderPage", "rider name:     "))
        self.label_6.setText(_translate("RiderPage", "rider Tel:      "))
        self.saveChange.setText(_translate("RiderPage", "save change"))
        self.abandonChange.setText(_translate("RiderPage", "abandon change"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_4), _translate("RiderPage", "personal information edit"))

