# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'riderpage.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_RiderPage(object):
    def setupUi(self, RiderPage):
        RiderPage.setObjectName("RiderPage")
        RiderPage.resize(800, 600)
        RiderPage.setMinimumSize(QtCore.QSize(800, 600))
        RiderPage.setMaximumSize(QtCore.QSize(800, 600))
        self.tabWidget = QtWidgets.QTabWidget(RiderPage)
        self.tabWidget.setGeometry(QtCore.QRect(0, 0, 800, 600))
        self.tabWidget.setMinimumSize(QtCore.QSize(800, 600))
        self.tabWidget.setMaximumSize(QtCore.QSize(800, 600))
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.tableWidget_order = QtWidgets.QTableWidget(self.tab)
        self.tableWidget_order.setGeometry(QtCore.QRect(30, 30, 731, 431))
        self.tableWidget_order.setObjectName("tableWidget_order")
        self.tableWidget_order.setColumnCount(6)
        self.tableWidget_order.setRowCount(3)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_order.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_order.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_order.setVerticalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_order.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_order.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_order.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_order.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_order.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_order.setHorizontalHeaderItem(5, item)
        self.horizontalLayoutWidget = QtWidgets.QWidget(self.tab)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(30, 490, 731, 51))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.acceptOrder = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.acceptOrder.setObjectName("acceptOrder")
        self.horizontalLayout.addWidget(self.acceptOrder)
        self.earlierOrder = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.earlierOrder.setObjectName("earlierOrder")
        self.horizontalLayout.addWidget(self.earlierOrder)
        self.laterOrder = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.laterOrder.setObjectName("laterOrder")
        self.horizontalLayout.addWidget(self.laterOrder)
        self.rejectOrder = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.rejectOrder.setObjectName("rejectOrder")
        self.horizontalLayout.addWidget(self.rejectOrder)
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.axWidget = QAxContainer.QAxWidget(self.tab_2)
        self.axWidget.setProperty("geometry", QtCore.QRect(10, 10, 771, 551))
        self.axWidget.setObjectName("axWidget")
        self.tabWidget.addTab(self.tab_2, "")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.tableWidget_historyOrder = QtWidgets.QTableWidget(self.tab_3)
        self.tableWidget_historyOrder.setGeometry(QtCore.QRect(30, 90, 731, 451))
        self.tableWidget_historyOrder.setObjectName("tableWidget_historyOrder")
        self.tableWidget_historyOrder.setColumnCount(5)
        self.tableWidget_historyOrder.setRowCount(3)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_historyOrder.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_historyOrder.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_historyOrder.setVerticalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_historyOrder.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_historyOrder.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_historyOrder.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_historyOrder.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_historyOrder.setHorizontalHeaderItem(4, item)
        self.horizontalLayoutWidget_2 = QtWidgets.QWidget(self.tab_3)
        self.horizontalLayoutWidget_2.setGeometry(QtCore.QRect(30, 20, 731, 51))
        self.horizontalLayoutWidget_2.setObjectName("horizontalLayoutWidget_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_2)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label = QtWidgets.QLabel(self.horizontalLayoutWidget_2)
        self.label.setObjectName("label")
        self.horizontalLayout_2.addWidget(self.label)
        self.comboBox_time = QtWidgets.QComboBox(self.horizontalLayoutWidget_2)
        self.comboBox_time.setObjectName("comboBox_time")
        self.comboBox_time.addItem("")
        self.comboBox_time.addItem("")
        self.comboBox_time.addItem("")
        self.comboBox_time.addItem("")
        self.horizontalLayout_2.addWidget(self.comboBox_time)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.lineEdit_timeStart = QtWidgets.QLineEdit(self.horizontalLayoutWidget_2)
        self.lineEdit_timeStart.setObjectName("lineEdit_timeStart")
        self.horizontalLayout_3.addWidget(self.lineEdit_timeStart)
        self.label_2 = QtWidgets.QLabel(self.horizontalLayoutWidget_2)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_3.addWidget(self.label_2)
        self.lineEdit_timeEnd = QtWidgets.QLineEdit(self.horizontalLayoutWidget_2)
        self.lineEdit_timeEnd.setObjectName("lineEdit_timeEnd")
        self.horizontalLayout_3.addWidget(self.lineEdit_timeEnd)
        self.horizontalLayout_2.addLayout(self.horizontalLayout_3)
        self.pushButton_filter = QtWidgets.QPushButton(self.horizontalLayoutWidget_2)
        self.pushButton_filter.setObjectName("pushButton_filter")
        self.horizontalLayout_2.addWidget(self.pushButton_filter)
        self.tabWidget.addTab(self.tab_3, "")
        self.tab_4 = QtWidgets.QWidget()
        self.tab_4.setObjectName("tab_4")
        self.formLayoutWidget = QtWidgets.QWidget(self.tab_4)
        self.formLayoutWidget.setGeometry(QtCore.QRect(80, 120, 631, 161))
        self.formLayoutWidget.setObjectName("formLayoutWidget")
        self.formLayout = QtWidgets.QFormLayout(self.formLayoutWidget)
        self.formLayout.setContentsMargins(0, 0, 0, 0)
        self.formLayout.setObjectName("formLayout")
        self.label_3 = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_3.setObjectName("label_3")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_3)
        self.riderID = QtWidgets.QLabel(self.formLayoutWidget)
        self.riderID.setText("")
        self.riderID.setObjectName("riderID")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.riderID)
        self.label_5 = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_5.setObjectName("label_5")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_5)
        self.lineEdit_riderName = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.lineEdit_riderName.setObjectName("lineEdit_riderName")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.lineEdit_riderName)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.formLayout.setItem(3, QtWidgets.QFormLayout.FieldRole, spacerItem)
        self.label_6 = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_6.setObjectName("label_6")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.label_6)
        self.lineEdit_riderTel = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.lineEdit_riderTel.setObjectName("lineEdit_riderTel")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.lineEdit_riderTel)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.formLayout.setItem(1, QtWidgets.QFormLayout.FieldRole, spacerItem1)
        self.horizontalLayoutWidget_4 = QtWidgets.QWidget(self.tab_4)
        self.horizontalLayoutWidget_4.setGeometry(QtCore.QRect(80, 380, 631, 71))
        self.horizontalLayoutWidget_4.setObjectName("horizontalLayoutWidget_4")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_4)
        self.horizontalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem2)
        self.saveChange = QtWidgets.QPushButton(self.horizontalLayoutWidget_4)
        self.saveChange.setObjectName("saveChange")
        self.horizontalLayout_4.addWidget(self.saveChange)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem3)
        self.abandonChange = QtWidgets.QPushButton(self.horizontalLayoutWidget_4)
        self.abandonChange.setObjectName("abandonChange")
        self.horizontalLayout_4.addWidget(self.abandonChange)
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem4)
        self.tabWidget.addTab(self.tab_4, "")

        self.retranslateUi(RiderPage)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(RiderPage)

    def retranslateUi(self, RiderPage):
        _translate = QtCore.QCoreApplication.translate
        RiderPage.setWindowTitle(_translate("RiderPage", "Dialog"))
        item = self.tableWidget_order.verticalHeaderItem(0)
        item.setText(_translate("RiderPage", "order01"))
        item = self.tableWidget_order.verticalHeaderItem(1)
        item.setText(_translate("RiderPage", "order02"))
        item = self.tableWidget_order.verticalHeaderItem(2)
        item.setText(_translate("RiderPage", "order03"))
        item = self.tableWidget_order.horizontalHeaderItem(0)
        item.setText(_translate("RiderPage", "user name"))
        item = self.tableWidget_order.horizontalHeaderItem(1)
        item.setText(_translate("RiderPage", "user Tel"))
        item = self.tableWidget_order.horizontalHeaderItem(2)
        item.setText(_translate("RiderPage", "order03"))
        item = self.tableWidget_order.horizontalHeaderItem(3)
        item.setText(_translate("RiderPage", "restaurant Loc"))
        item = self.tableWidget_order.horizontalHeaderItem(4)
        item.setText(_translate("RiderPage", "distance"))
        item = self.tableWidget_order.horizontalHeaderItem(5)
        item.setText(_translate("RiderPage", "order_state"))
        self.acceptOrder.setText(_translate("RiderPage", "accept"))
        self.earlierOrder.setText(_translate("RiderPage", "earlier"))
        self.laterOrder.setText(_translate("RiderPage", "later"))
        self.rejectOrder.setText(_translate("RiderPage", "reject"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("RiderPage", "orders waiting"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("RiderPage", "navigation"))
        item = self.tableWidget_historyOrder.verticalHeaderItem(0)
        item.setText(_translate("RiderPage", "order01"))
        item = self.tableWidget_historyOrder.verticalHeaderItem(1)
        item.setText(_translate("RiderPage", "order02"))
        item = self.tableWidget_historyOrder.verticalHeaderItem(2)
        item.setText(_translate("RiderPage", "order03"))
        item = self.tableWidget_historyOrder.horizontalHeaderItem(0)
        item.setText(_translate("RiderPage", "user ID"))
        item = self.tableWidget_historyOrder.horizontalHeaderItem(1)
        item.setText(_translate("RiderPage", "rest ID"))
        item = self.tableWidget_historyOrder.horizontalHeaderItem(2)
        item.setText(_translate("RiderPage", "distance"))
        item = self.tableWidget_historyOrder.horizontalHeaderItem(3)
        item.setText(_translate("RiderPage", "order time"))
        item = self.tableWidget_historyOrder.horizontalHeaderItem(4)
        item.setText(_translate("RiderPage", "delivered time"))
        self.label.setText(_translate("RiderPage", "filter by time: "))
        self.comboBox_time.setItemText(0, _translate("RiderPage", "all orders"))
        self.comboBox_time.setItemText(1, _translate("RiderPage", "orders in this year"))
        self.comboBox_time.setItemText(2, _translate("RiderPage", "orders in this month"))
        self.comboBox_time.setItemText(3, _translate("RiderPage", "orders in this week"))
        self.label_2.setText(_translate("RiderPage", "to"))
        self.pushButton_filter.setText(_translate("RiderPage", "filter"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("RiderPage", "orders delivered"))
        self.label_3.setText(_translate("RiderPage", "rider ID:      "))
        self.label_5.setText(_translate("RiderPage", "rider name:     "))
        self.label_6.setText(_translate("RiderPage", "rider Tel:      "))
        self.saveChange.setText(_translate("RiderPage", "save change"))
        self.abandonChange.setText(_translate("RiderPage", "abandon change"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_4), _translate("RiderPage", "personal information edit"))

from PyQt5 import QAxContainer
